# Generated by Django 3.1.4 on 2020-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_year', models.SmallIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=30)),
                ('cast', models.TextField()),
                ('genre', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('plot', models.TextField()),
            ],
        ),
    ]
