# Generated by Django 3.1.4 on 2020-12-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20201202_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default='', max_length=100),
        ),
    ]
